import os
import torch
import torch.nn as nn

# ---> PASTE YOUR CoLoRA_Dynamics AND HyperNetwork CLASSES HERE <---
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

class Periodic(nn.Module):
    def __init__(self, in_features, width, period, with_bias=True, frequency_scale=30.0):
        """
        PyTorch version of the JAX Periodic layer.
        """
        super().__init__()
        self.width = width
        self.in_features = in_features
        self.with_bias = with_bias
        
        # Period: JAX uses jnp.asarray(self.period), assume it's a list/array
        # We buffer it so it doesn't update, but moves to device
        if period is not None:
            self.register_buffer('period', torch.tensor(period, dtype=torch.float32))
        else:
            self.period = None

        # Initialization logic (LeCun Normal approx: std = 1/sqrt(fan_in))
        std = 1.0 / np.sqrt(in_features)
        std = frequency_scale / np.sqrt(in_features)
        
        # Params: (Width, Dim) matches JAX shape
        self.a = nn.Parameter(torch.randn(width, in_features) * std)
        self.phi = nn.Parameter(torch.randn(width, in_features) * std)
        
        if with_bias:
            self.b = nn.Parameter(torch.randn(width, in_features) * std)
        else:
            self.register_parameter('b', None)

    def forward(self, x):
        # x: (Batch, Dim)
        # Params: (Width, Dim)
        
        # 1. Expand for Broadcasting
        # x: (B, 1, D)
        # params: (1, W, D)
        x_exp = x.unsqueeze(1) 
        a_exp = self.a.unsqueeze(0)
        phi_exp = self.phi.unsqueeze(0)
        
        # 2. Compute Omega
        # omeg = 2pi / period
        # Reshape period to broadcast if necessary, usually scalar or (Dim,)
        omeg = (2 * torch.pi) / self.period
        # If period is per-dimension, ensure shape aligns (1, 1, D)
        if omeg.ndim == 1:
            omeg = omeg.view(1, 1, -1)
            
        # 3. The Formula: a * cos(omeg * x + phi)
        # Shape: (B, W, D)
        val = omeg * x_exp + phi_exp
        o = a_exp * torch.cos(val)
        
        if self.with_bias:
            o = o + self.b.unsqueeze(0)
            
        # 4. Mean over the input dimension (Dim)
        # JAX: jnp.mean(o, axis=1) -> usually implies reduction over the 'dim' axis 
        # given the (Width, Dim) setup.
        o = torch.mean(o, dim=-1) # Result: (Batch, Width)
        
        return o

class CoLoRALayer(nn.Module):
    def __init__(self, in_features, out_features, rank, full=True, with_bias=True):
        """
        PyTorch version of JAX CoLoRA layer.
        """
        super().__init__()
        self.in_features = in_features
        self.out_features = out_features
        self.rank = rank
        self.full = full
        self.with_bias = with_bias
        
        # 1. Base Weight 'W' (D, K)
        # Init: LeCun Normal
        std_w = 1.0 / np.sqrt(in_features)
        self.W = nn.Parameter(torch.randn(in_features, out_features) * std_w)
        
        # 2. LoRA Params
        # A: (D, r), B: (r, K)
        self.A = nn.Parameter(torch.randn(in_features, rank) * std_w)
        self.B = nn.Parameter(torch.randn(rank, out_features)* std_w) # Zero init for B
        
        # 3. Bias
        if with_bias:
            self.b = nn.Parameter(torch.zeros(out_features))
        else:
            self.register_parameter('b', None)
            
        # Note: Internal 'alpha' param is skipped here because 
        # you are generating it via Hypernetwork.

    def forward(self, x, alpha):
        """
        x: (Batch, In)
        alpha: (Batch, Rank) - Generated by Hypernetwork
        """
        # Dimensions
        # D = in, K = out, r = rank
        
        # 1. Compute LoRA Term: (A * alpha) @ B
        # A: (D, r) -> (1, D, r)
        # alpha: (B, r) -> (B, 1, r)
        # B: (r, K)
        
        # Scale Columns of A: (B, D, r)
        A_scaled = self.A.unsqueeze(0) * alpha.unsqueeze(1)
        
        # Multiply by B: (B, D, r) @ (r, K) -> (B, D, K)
        AB = torch.matmul(A_scaled, self.B)
        
        # 2. Add to Base Weight W
        # W: (D, K) -> (1, D, K)
        # W_effective = W + AB
        W_effective = self.W.unsqueeze(0) + AB
        
        # 3. Apply Linear: x @ W_effective
        # x: (B, D) -> (B, 1, D)
        # (B, 1, D) @ (B, D, K) -> (B, 1, K)
        out = torch.bmm(x.unsqueeze(1), W_effective).squeeze(1)
        
        if self.with_bias:
            out = out + self.b
            
        return out

class CoLoRA_Dynamics(nn.Module):
    def __init__(self, latent_dim_crom, hidden_dim=256, depth=3, rank=1):
        super().__init__()
        
        # --- CHANGE 1: Add the Periodic Embedding ---
        # This converts t (1 dim) into a rich waveform representation (hidden_dim)
        # We assume t is normalized [0, 1], so period=1.0 covers the whole domain.
        self.embedding = Periodic(in_features=1, width=hidden_dim, period=[1.0])
        
        self.layers = nn.ModuleList()
        
        # --- CHANGE 2: Update First Layer Input ---
        # WAS: CoLoRALayer(1, hidden_dim, rank)
        # NOW: Input is 'hidden_dim' (coming from the Periodic layer)
        self.layers.append(CoLoRALayer(hidden_dim, hidden_dim, rank))
        
        # Hidden -> Hidden
        for _ in range(depth - 1):
            self.layers.append(CoLoRALayer(hidden_dim, hidden_dim, rank))
            
        # Hidden -> Output (CROM Latent)
        self.layers.append(CoLoRALayer(hidden_dim, latent_dim_crom, rank))
        
        self.activation = nn.SiLU() 

    def forward(self, t, alphas_list):
        # --- CHANGE 3: Apply Embedding First ---
        # t: (Batch, 1) -> x: (Batch, hidden_dim)
        x = self.embedding(t)
        
        # The rest acts on this high-dimensional feature vector
        for i, layer in enumerate(self.layers):
            x = layer(x, alphas_list[i])
            if i < len(self.layers) - 1:
                x = self.activation(x)
        return x

class HyperNetwork(nn.Module):
    def __init__(self, param_dim, num_target_layers, rank):
        super().__init__()
        self.rank = rank
        self.num_target_layers = num_target_layers
        self.output_dim = num_target_layers * rank
        
        # Simple MLP: Params -> Alphas
        self.net = nn.Sequential(
            nn.Linear(param_dim, 64),
            nn.SiLU(),
            nn.Linear(64, 64),
            nn.SiLU(),
            nn.Linear(64, self.output_dim)
        )

    def forward(self, mu):
        # mu: (Batch, Param_Dim)
        raw = self.net(mu)
        # Split into list for each layer: List of (Batch, Rank)
        return torch.split(raw, self.rank, dim=1)

class CoLoRA_Wrapper:
    def __init__(self, args, device):
        self.args = args
        self.device = device
        
        print(f"\n--- Initializing CoLoRA ---")
        self.decoder = torch.jit.load(args.dec, map_location=device).eval()
        
        print(f"Loading Checkpoint: {os.path.basename(args.ckpt)}")
        ckpt = torch.load(args.ckpt, map_location=device)
        
        c_args = ckpt['args']
        self.latent_dim = ckpt['latent_dim']
        self.param_dim = ckpt.get('param_dim', 1)
        
        depth = c_args.depth
        # IMPORTANT: Ensure CoLoRA_Dynamics and HyperNetwork are defined above or imported
        self.dynamics = CoLoRA_Dynamics(self.latent_dim, c_args.hidden_dim, depth, c_args.rank).to(device)
        self.hypernet = HyperNetwork(self.param_dim, depth + 1, c_args.rank).to(device)
        
        self.dynamics.load_state_dict(ckpt['dynamics_state'])
        self.hypernet.load_state_dict(ckpt['hypernet_state'])
        
        self.dynamics.eval()
        self.hypernet.eval()

    def predict(self, frame_idx, total_frames, sim_idx, total_sims, x_ref):
        with torch.no_grad():
            t_val = frame_idx / max(1, total_frames - 1)
            t = torch.tensor([[t_val]], device=self.device, dtype=torch.float32)
            
            mu_val = sim_idx / max(1, total_sims - 1)
            mu = torch.tensor([[mu_val]], device=self.device, dtype=torch.float32)

            alphas = self.hypernet(mu)
            z_pred = self.dynamics(t, alphas)
            
            N_full = x_ref.size(0)
            z_expanded = z_pred.unsqueeze(1).expand(-1, N_full, -1)
            ref_expanded = x_ref.unsqueeze(0)
            
            dec_in = torch.cat([z_expanded, ref_expanded], dim=2)
            dec_in_flat = dec_in.view(-1, dec_in.size(2))
            
            pred = self.decoder(dec_in_flat)
            return pred.view(N_full, 3)