hidden_size: 128
n_mp_layers: 10                                        
num_particle_types: 9
particle_type_dim: 16                                                     
dim: 2                                                                   
window_size: 5                                                            
heads : 3                                                                 
n_modes: !!python/tuple
- 24
- 24                                                      
fno_in_channels: 2
fno_hidden_channels: 64
fno_lifting_channels: 256
fno_projection_channels: 256
fno_layers: 4
fno_use_mlp: true
fno_stabilizers: 'tanh'
fno_preactivation: true

use_open3d: false                                                       
in_gno_mlp_hidden_layers: 
- 32
- 64
in_gno_transform_type: 'nonlinear_kernelonly'
out_gno_in_dim: 2
out_gno_hidden: 128
out_gno_mlp_hidden_layers: 
- 512
- 256

gno_radius: 0.00045
out_gno_transform_type: 'linear'

projection_channels: 256
projection_layers: 2
projection_n_dim: 1

latent_grid_dim: 32
latent_domain_lims:
- - -1.0
  - 1.0
- - -1.0
  - 1.0
