batch_size: 4
ckpt_name: giorom2d_T_WaterDropSmall
dataset: WaterDropSmall
dataset_rootdir: /home/csuser/Documents/new_dataset/
epoch: 2000
eval_interval: 1500
load_checkpoint: true
lr: 0.0001
gamma: 0.1**(1/5e6)
model: dino
noise: 0
sampling: false
sampling_strategy: random
graph_type: radius
rollout_interval: 1500
connectivity_radius: 0.032
save_interval: 1000
store_loss: true
visualize_graph: true
model_config: dino.yaml
save_weights: false
