import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import os
import sys

# --- DYNAMIC PATH CONFIGURATION ---
# Resolve the project root (assuming this script is in online_rom/scripts/)
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESULTS_DIR = os.path.join(PROJECT_ROOT, "results", "raw_metrics")
OUT_DIR = os.path.join(PROJECT_ROOT, "visualizations", "media")

# --- CONFIGURATION ---
DATASET_NAME = "owl"  
GRID_SIZES = [20, 32, 64, 82, 100]
SPARSITIES = [12, 14, 18, 20, 24, 36, 48, 60, 72, 100]

def load_ablation_data():
    """
    Reads the individual CSV files generated by the benchmarking script
    and aggregates them into two DataFrames for plotting.
    """
    
    # 1. Load Grid Ablation Data
    grid_data = []
    for g in GRID_SIZES:
        # Check both naming conventions just in case
        fname_upper = os.path.join(RESULTS_DIR, f"{DATASET_NAME}_giorom_Grid_{g}.csv")
        fname_lower = os.path.join(RESULTS_DIR, f"{DATASET_NAME}_giorom_grid_{g}.csv")
        fname = fname_upper if os.path.exists(fname_upper) else fname_lower
        
        if os.path.exists(fname):
            df = pd.read_csv(fname)
            row = {
                "Grid_Size": g,
                "L2_Mean": df["RelL2_Mean"].mean(),
                "L2_Std": df["RelL2_Mean"].std(), 
                "Time_Mean": df["Time_ms"].mean(),
                "VRAM": df["vram_MB"].mean()
            }
            grid_data.append(row)
        else:
            print(f"Warning: Missing grid data for {g} at {fname}")

    # 2. Load Sparsity Ablation Data
    sparsity_data = []
    for s in SPARSITIES:
        fname = os.path.join(RESULTS_DIR, f"{DATASET_NAME}_giorom_sampling_{s}.csv")
        
        if os.path.exists(fname):
            df = pd.read_csv(fname)
            row = {
                "Sparsity": s,
                "L2_Mean": df["RelL2_Mean"].mean(),
                "L2_Std": df["RelL2_Mean"].std(),
                "Time_Mean": df["Time_ms"].mean(),
                "VRAM": df["vram_MB"].mean()
            }
            sparsity_data.append(row)
        else:
            print(f"Warning: Missing sparsity data for {s} at {fname}")

    return pd.DataFrame(grid_data), pd.DataFrame(sparsity_data)

def plot_ablation_panels():
    # -------------------------------------------------------
    # 1. LOAD DATA
    # -------------------------------------------------------
    df_grid, df_sparse = load_ablation_data()
    
    if df_grid.empty or df_sparse.empty:
        print("Error: No data loaded. Check CSV filenames/paths.")
        return

    # -------------------------------------------------------
    # 2. CUSTOM AESTHETICS
    # -------------------------------------------------------
    sns.set_theme(style="white", context="paper")
    
    # Font Setup
    plt.rcParams['font.family'] = 'serif'
    plt.rcParams['font.serif'] = ['Baskerville', 'Times New Roman', 'DejaVu Serif']
    
    # Custom Palette
    c_gio = "#4D8585"   # Muted Teal for GIOROM

    # Setup 1x2 Grid
    fig, axes = plt.subplots(1, 2, figsize=(12, 5), dpi=300)
    plt.subplots_adjust(wspace=0.25)

    # -------------------------------------------------------
    # PANEL 1: GRID RESOLUTION ABLATION
    # -------------------------------------------------------
    ax1 = axes[0]
    ax1.grid(True, linestyle='--', alpha=0.3)

    # Plot Line
    ax1.plot(df_grid["Grid_Size"], df_grid["L2_Mean"], 
             color=c_gio, linewidth=2.5, marker='s', markersize=7, 
             label="GIOROM Error")
    
    # Add Error Region (Mean ± Std)
    ax1.fill_between(df_grid["Grid_Size"], 
                     df_grid["L2_Mean"] - df_grid["L2_Std"], 
                     df_grid["L2_Mean"] + df_grid["L2_Std"], 
                     color=c_gio, alpha=0.15)

    # Labels
    ax1.set_title("a. Impact of Grid Resolution", fontsize=12, fontweight='bold', pad=10)
    ax1.set_xlabel("Grid Resolution ($R^3$)", fontsize=10)
    ax1.set_ylabel("Relative L2 Error", fontsize=10)
    
    # Formatting Y-axis to percentage
    ax1.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f'{x:.1%}'))
    
    # -------------------------------------------------------
    # PANEL 2: SPARSITY FACTOR ABLATION
    # -------------------------------------------------------
    ax2 = axes[1]
    ax2.grid(True, linestyle='--', alpha=0.3)

    # Plot Line
    ax2.plot(df_sparse["Sparsity"], df_sparse["L2_Mean"], 
             color=c_gio, linewidth=2.5, marker='o', markersize=7, 
             label="GIOROM Error")
    
    # Add Error Region
    ax2.fill_between(df_sparse["Sparsity"], 
                     df_sparse["L2_Mean"] - df_sparse["L2_Std"], 
                     df_sparse["L2_Mean"] + df_sparse["L2_Std"], 
                     color=c_gio, alpha=0.15)

    # Labels
    ax2.set_title("b. Impact of Sparsity Factor", fontsize=12, fontweight='bold', pad=10)
    ax2.set_xlabel("Sparsity Factor (1/S)", fontsize=10)
    ax2.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f'{x:.1%}'))
    
    # -------------------------------------------------------
    # SAVE
    # -------------------------------------------------------
    os.makedirs(OUT_DIR, exist_ok=True)
    pdf_path = os.path.join(OUT_DIR, "ablation_grid_sparsity.pdf")
    png_path = os.path.join(OUT_DIR, "ablation_grid_sparsity.png")
    
    plt.tight_layout()
    plt.savefig(pdf_path, format='pdf', bbox_inches='tight')
    plt.savefig(png_path, format='png', bbox_inches='tight', dpi=300)
    print(f"Plots saved successfully to:\n  - {pdf_path}\n  - {png_path}")

if __name__ == "__main__":
    plot_ablation_panels()