# Training Configuration for Giorom3D Model

batch_size: 2  # Number of samples per training batch

# Model Checkpointing
ckpt_name: checkpoint-550000  # Name of the checkpoint to save/load
load_checkpoint: true  # Whether to load a pre-existing checkpoint

# Dataset Settings
dataset: Sand3D_long  # Name of the dataset
dataset_rootdir: hrishivish23/MPM-Verse-MaterialSim-Small  # Root directory for the dataset
cache_dir: dataset_mpmverse  # Directory to cache the dataset

# Training Parameters
is_train: true  # Whether the model is in training mode
epoch: 2000  # Number of training epochs
lr: 0.00007  # Learning rate
weight_decay: 0.000001  # Weight decay for optimizer regularization
gamma: 0.1**(1/5e6)  # Learning rate decay factor
noise: 0.000003  # Amount of noise added to input data (for regularization)

# Model Configuration
model: giorom3d_T  # Model name
model_config: giorom3d_T.yaml  # Path to the model-specific config file

# Sampling Strategy
sampling: false  # Whether to use data sampling
sampling_strategy: random  # Sampling method (e.g., random, stratified)

# Graph-based Connectivity
graph_type: radius  # Type of graph connectivity (e.g., 'radius', 'knn')
connectivity_radius: 0.105  # Radius for graph connections

# Evaluation & Logging
eval_interval: 1500  # Interval (steps) at which evaluation is performed
rollout_interval: 1500  # Interval for rollout evaluation
log_interval: 1500  # Interval (steps) for logging metrics
save_interval: 110000  # Interval (steps) for saving model checkpoints
visualize_graph: false  # Whether to visualize graph connections
