hidden_size: 128
n_mp_layers: 2                                                           # number of GNN layers
num_particle_types: 9
particle_type_dim: 16                                                     # embedding dimension of particle types
dim: 3                                                                    # dimension of the world typical 2D or 3D
window_size: 5                                                            # the model looks into W frames before the frame to be predicted
heads : 3                                                                 # number of attention heads in GAT and EGAT

use_open3d : false                                                       #GNO Hyperparams
in_gno_mlp_hidden_layers :
- 32
- 64
in_gno_transform_type : 'nonlinear_kernelonly'
out_gno_in_dim : 3
out_gno_hidden: 128
out_gno_mlp_hidden_layers : 
- 32
- 64

gno_radius: 0.125 #Only for Sand
out_gno_transform_type: 'linear'

not_heads: 4
not_layers: 1
not_output_size: 128
not_space_dim: 64
not_branch_size: 3
not_trunk_size: 64

projection_channels: 256
projection_layers: 1
projection_n_dim : 1

latent_grid_dim : 16
latent_domain_lims : 
- - 0.0
  - 1.0
- - 0.0
  - 1.0
- - 0.0
  - 1.0
