batch_size: 2
ckpt_name: giorom3d_large_nclaw_Water
dataset: nclaw_Water
dataset_rootdir: /home/csuser/Documents/new_dataset/
epoch: 2000
eval_interval: 1500
load_checkpoint: true
lr: 0.0001
gamma: 0.1**(1/5e6)
model: giorom3d_large
noise: 0.0003
sampling: false
sampling_strategy: random
graph_type: radius
connectivity_radius: 0.12499999672174454
rollout_interval: 1500
save_interval: 1000
store_loss: true
visualize_graph: false
model_config: giorom3d_large.yaml
