batch_size: 2
ckpt_name: fom_gno_nclaw_Sand
dataset: nclaw_Sand
dataset_rootdir: /home/csuser/Documents/new_dataset/
epoch: 2000
eval_interval: 1500
load_checkpoint: true
lr: 0.0001
gamma: 0.1**(1/5e6)
model: fom_gno
noise: 0.0003
sampling: true
train_on_displacement: false
sampling_strategy: random
graph_type: radius
connectivity_radius: 0.01
sample_mesh_size: 3000
save_interval: 1000
store_loss: true
visualize_graph: false
model_config: fom_gno_nclaw_Sand.yaml
save_weights: true
