batch_size: 2
ckpt_name: giorom3d_T_owl
dataset: owl
dataset_rootdir: /home/csuser/Documents/new_dataset/
epoch: 2000
eval_interval: 1500
load_checkpoint: true
lr: 0.0001
gamma: 0.1**(1/5e6)
model: giorom3d_T
noise: 0.0
rollout_interval: 1500
connectivity_radius: 0.060
save_interval: 1000
sampling: false
sampling_strategy: random
graph_type: radius
store_loss: true
visualize_graph: false
model_config: giorom3d_T.yaml
save_weights: false
