batch_size: 4
ckpt_name: giorom2d_WaterDropSmall_sampled
dataset: WaterDropSmall
dataset_rootdir: /home/csuser/Documents/new_dataset/
epoch: 2000
eval_interval: 1500
load_checkpoint: true
lr: 0.0001
gamma: 0.1**(1/5e6)
model: giorom2d
noise: 0.0003
sampling: true
sampling_strategy: random
graph_type: radius
rollout_interval: 1500
save_interval: 1000
store_loss: true
visualize_graph: true
model_config: giorom2d.yaml
