batch_size: 2
ckpt_name: giorom3d_T_elasticity
dataset: elasticity
dataset_rootdir: /home/csuser/Documents/new_dataset/
epoch: 2000
eval_interval: 1500
load_checkpoint: true
lr: 0.0001
gamma: 0.1**(1/5e6)
model: giorom3d_T
noise: 0
sampling: false
sampling_strategy: random
graph_type: radius
rollout_interval: 1500
connectivity_radius: 0.085
save_interval: 1000
store_loss: true
visualize_graph: false
model_config: giorom3d_T.yaml
