batch_size: 4
ckpt_name: giorom3d_plasticine_nclaw
dataset: plasticine_nclaw
dataset_rootdir: /home/csuser/Documents/new_dataset/
epoch: 2000
eval_interval: 1500
load_checkpoint: true
lr: 0.0001
gamma: 0.1**(1/5e6)
model: giorom3d
noise: 0.0001
sampling_strategy: random
graph_type: radius
rollout_interval: 150
save_interval: 1000
store_loss: true
visualize_graph: false
model_config: giorom3d.yaml
