batch_size: 4
ckpt_name: giorom3d_large_nclaw_Plasticine
dataset: nclaw_Plasticine
dataset_rootdir: /home/csuser/Documents/new_dataset/
epoch: 2000
eval_interval: 15500
load_checkpoint: true
lr: 0.0001
gamma: 0.1**(1/5e6)
model: giorom3d_large
noise: 0.0003
random_sampling: false
rollout_interval: 15500
save_interval: 1000
store_loss: true
visualize_graph: false
model_config: giorom3d_large.yaml
