batch_size: 2
ckpt_name: giorom3d_T_nclaw_Sand
dataset: nclaw_Sand
dataset_rootdir: /home/csuser/Documents/new_dataset/
epoch: 2000
eval_interval: 1500
load_checkpoint: true
lr: 0.0001
gamma: 0.1**(1/5e6)
model: giorom3d_T
noise: 0.000003
sampling: false
sampling_strategy: random
graph_type: radius
connectivity_radius: 0.105
rollout_interval: 1500
save_interval: 1000
store_loss: true
visualize_graph: false
model_config: giorom3d_T.yaml
